### ISSUE TITLE
allow for lower polling interval

### ISSUE THREAD

**Issue by kaohlive** [MaxvandeLaar/homey-webos-plus#11] opened 2020-03-23 23:57 UTC
You have the minimum polling interval set to 120s.
In my opinion this is to long to detect on/off state since it makes the reaction to events way to slow.
Can you allow me to set my polling to a lower value?

**Comment by MaxvandeLaar** [comment] 2020-03-24 08:27
@kaohlive, yes and no. 

It's obviously easy for me to change the minimum polling interval, however, I have much thought about that before releasing the first version and I have experimented with lower intervals. The problem is, Homey doesn't allow for pings and at the moment I check the mac address of the IP address of the recognised tv as a ping mechanism. 

This takes some time, and if you turn on/off the tv via Homey or something that controls Homey, the on/off state will toggle a few times until the 'ping check' resolves with the final answer. Furthermore, it takes some time before the TV disconnects from the network, resulting that the 'ping check' will be true for quiet some time even though the TV seems to be turned off.

So allowing this makes the on/off state unreliable for flows. I am always willing to look into every enhancement, however, this can cause major issues if not set correctly by the use; so I am very reluctant. 

If I would allow it, users should be aware that I won't be able to guarantee a correct working state and I am unable to give support for that. I don't want to be flooded with issues about flows not responding well due to bad state of the WebOS app. This is actually a problem for the official one. 

To not totally disregard your request, what would be a minimum time for you, and why would you need it to be faster?

**Comment by kaohlive** [comment] 2020-03-24 09:33
so i am trying to make some alexa voice control for the tv. so i created a virtual switch on/off that can be seen by alexa skill. then when alexa turns this vd on i turn on the tv and vice versa. to ensure proper status i also use a tv on/off trigger to set the vd in the same state.
next i have a trigger that when the vd gets turned on and no input is selected on the tv or its off it can turn it on and launch the live tv app. 

these flows work poorly due to the long wrong state of the device if someone used the remote. 

also i am suffering from the device sometimes turning on after i went to bed because of the delayed states. 

so reducing the state lag would be a great thing. but i do heae what you say on the toggling on off between command and actuall state. 

on my xbox app i need to use an open socket so the disconnect is a nice poweroff event. on my new motion app i do the same as you, long interval. so i understand your challenges. 

another thing i was hoping todo waa to make a default app launch when the tv is turned on since i hate that it gives the no input signal as default behavior.

**Comment by MaxvandeLaar** [comment] 2020-03-24 09:42
I do have another option to check state which is even more reliable then polling. I don't want to get into detail but according to my initial (short) tests it would vastly increase performance and stability. So polling won't be longer a thing. However, this won't be implemented yet as I first want to release v1.3.0

**Closed by MaxvandeLaar** 2020-03-24 09:42 UTC
Labels: enhancement

**Comment by OllemGit** [comment] 2020-03-24 10:29
Did you have a look at Nmap command? 
This app is based on this:
https://homey.app/nl-nl/app/nl.terryhendrix.netscan/Net-Scan/

**Comment by MaxvandeLaar** [comment] 2020-03-24 10:33
Yes I did, can't remember why that didn't worked out. But as stated above, I probably have a different solution and even better, its part of the WebOS api 😉

**Comment by OllemGit** [comment] 2020-03-24 10:39
Even better than! :-)

**Comment by MaxvandeLaar** [comment] 2020-03-26 13:10
@kaohlive @OllemGit Just a quick update on the rewrite and on/off state timing.

With the new method of listening for state changes I timed (just once) how long it takes state changes to be detected in the app if the tv is turned on/off with the remote control instead of an app (such as Homey or Homekit). 

From on to off: it's pretty much instant (say 1 or 2 seconds)

From off to on: it took 55 seconds. It takes a while before the tv opens op the network connect and the app has a timeout of 15 seconds and retries every 5 seconds to connect. So experiences will probably vary based on your tv, network, and chance.
